//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_LOSS_SOUNDS2Entities : DbContext
    {
        public BD_LOSS_SOUNDS2Entities()
            : base("name=BD_LOSS_SOUNDS2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Album> tb_Album { get; set; }
        public virtual DbSet<tb_Artista> tb_Artista { get; set; }
        public virtual DbSet<tb_Cancion> tb_Cancion { get; set; }
        public virtual DbSet<tb_Playlist> tb_Playlist { get; set; }
        public virtual DbSet<tb_RolesPrivacidad> tb_RolesPrivacidad { get; set; }
        public virtual DbSet<tb_Usuario> tb_Usuario { get; set; }
    }
}
