//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
<<<<<<< HEAD
    public partial class BD_LOSS_SOUNDSEntities : DbContext
    {
        public BD_LOSS_SOUNDSEntities()
            : base("name=BD_LOSS_SOUNDSEntities")
=======
    public partial class BD_LOSS_SOUNDSEntities1 : DbContext
    {
        public BD_LOSS_SOUNDSEntities1()
            : base("name=BD_LOSS_SOUNDSEntities1")
>>>>>>> 34e47eda0313c6bb3798fb4b5dae8ad45bc1ca00
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_Album> tb_Album { get; set; }
        public DbSet<tb_Artista> tb_Artista { get; set; }
        public DbSet<tb_Cancion> tb_Cancion { get; set; }
        public DbSet<tb_Playlist> tb_Playlist { get; set; }
        public DbSet<tb_RolesPrivacidad> tb_RolesPrivacidad { get; set; }
        public DbSet<tb_Usuario> tb_Usuario { get; set; }
    }
}
